/*
 * project_conf.h
 *
 *  Created on: 18.06.2017
 *      Author: Philipp
 */

#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#define TRUE 1
#define FALSE 0

//Debugging
#define MODULE_1_USE_VIRTUAL_INPUT TRUE
#define MODULE_1_USE_VIRTUAL_OUTPUT TRUE
#define MODULE_2_USE_VIRTUAL_INPUT TRUE
#define MODULE_2_USE_VIRTUAL_OUTPUT TRUE
#define MODULE_3_USE_VIRTUAL_INPUT TRUE
#define MODULE_3_USE_VIRTUAL_OUTPUT TRUE
#define MODULE_4_USE_VIRTUAL_INPUT TRUE
#define MODULE_4_USE_VIRTUAL_OUTPUT TRUE
#define MODULE_5_USE_VIRTUAL_INPUT TRUE
#define MODULE_5_USE_VIRTUAL_OUTPUT TRUE
#define MODULE_6_USE_VIRTUAL_INPUT TRUE
#define MODULE_6_USE_VIRTUAL_OUTPUT TRUE
#define MODULE_7_USE_VIRTUAL_INPUT TRUE
#define MODULE_7_USE_VIRTUAL_OUTPUT TRUE




#endif /* PROJECT_CONF_H_ */
