/*
 * project_conf.h
 *
 *  Created on: 18.06.2017
 *      Author: Philipp
 */

#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#define TRUE 1
#define FALSE 0

//Debugging
#define MODULE_1_USE_VIRTUAL_INPUT FALSE
#define MODULE_1_USE_VIRTUAL_OUTPUT TRUE
#define MODULE_2_USE_VIRTUAL_INPUT FALSE
#define MODULE_2_USE_VIRTUAL_OUTPUT TRUE
#define MODULE_3_USE_VIRTUAL_INPUT FALSE
#define MODULE_3_USE_VIRTUAL_OUTPUT TRUE
#define MODULE_4_USE_VIRTUAL_INPUT FALSE
#define MODULE_4_USE_VIRTUAL_OUTPUT TRUE
#define MODULE_5_USE_VIRTUAL_INPUT FALSE
#define MODULE_5_USE_VIRTUAL_OUTPUT TRUE
#define MODULE_6_USE_VIRTUAL_INPUT FALSE
#define MODULE_6_USE_VIRTUAL_OUTPUT TRUE
#define MODULE_7_USE_VIRTUAL_INPUT FALSE
#define MODULE_7_USE_VIRTUAL_OUTPUT TRUE

#define MODULE_ID_NONE
#define MODULE_ID_TRANSPORT 1
#define MODULE_ID_GRAVITY 2
#define MODULE_ID_PUMPING 3
#define MODULE_ID_POURING 4
#define MODULE_ID_SENSORS 5
#define MODULE_ID_HANDLING 6
#define MODULE_ID_ICE 7

//Wenn hier eine Zahl auﬂer -1 steht, wird ein einzelnen Modul getestet
#define SINGLE_MODULE_TEST MODULE_ID_ICE

//Gewichte und Faktoren
#define FACTOR_BITS_TO_GRAMMS 1.46 //TODO Anpassen
#define FACTOR_BITS_TO_ANGLE 360/4096
#define FACTOR_BITS_TO_POSITION 8/4096
#define OFFSET_WEIGHT 1670
#define GLASS_WEIGHT 100

//Timeouts
#define TIMEOUT_ICE_FILL 20000




#endif /* PROJECT_CONF_H_ */
